title: Şaban DEMİRCİ
description: >
  **I am Şaban**, GIS developer, JavaScript enthusiast, JAVA coder.
copyright: sabandemirci
sass:
  sass_dir: assets/sass
url: http://localhost:4000
disqus_shortname: "sabandemirci"
facebook_username:
twitter_username: "sabandemirci"
linkedin_username: "şaban-demirci-50ab552a"
instagram_username: "demirci.saban"
pinterest_username: "demircisaban"
flickr_username:
github_username:  "sabandemirci"
feed_icon: rss
email: "sabandmirci@gmail.com"
plugins: [jekyll-paginate]
paginate_path: "/page/:num/"
paginate: 5
